### ISSUE TITLE
Missing modules on initramfs generation after kernel update.

### ISSUE THREAD

**Issue by nemasu** [nemasu/noop-linux#1]
After a kernel update, the initramfs is regenerated. This will cause problems if you have other packages installed that provide modules (like nvidia, virtualbox, etc) and that are included in the initramfs. 

Current workaround is regenerating initramfs after you reboot and update these other packages.

**Comment by ghost** [comment]
use dracut?

**Comment by nemasu** [comment]
Yeah, there's an option to use dracut, but I haven't tested it much.
I think...i need to specify new kernel version or something, haven't looked into it in a while.

**Comment by nemasu** [comment]
FIxed, mkinitramfs or dracut update is called automatically after pkgr -U is finished and there was a kernel update.
