### ISSUE TITLE
Locale generation

### ISSUE THREAD

**Issue by nemasu** [nemasu/noop-linux#3]
Currently we're generating all locales when glibc is installed/upgraded. This may not be the best idea.

**Comment by ghost** [comment]
use locale-gen from debian/gentoo/arch

**Comment by nemasu** [comment]
Ah, I'd probably just integrate it into pkgr. I just haven't decided whether to use an opt-in config file or what the default settings would be.

**Comment by nemasu** [comment]
Fixed in latest version of glibc. Needs documentation though.
