### ISSUE TITLE
Update the plasma livecd ?

### ISSUE THREAD

**Issue by DraGiuS** [nemasu/noop-linux#4]

**Comment by nemasu** [comment]
Hello, livecd should be 5.12.4 the website has a typo(says 5.14.4).
Ill see if I can update to 5.13.4 this week.

**Comment by DraGiuS** [comment]
Can you add steam, kdenlive and libreoffice on the livecd ?

**Comment by nemasu** [comment]
I'll add kdenlive, Libreoffice should already be on there.  Steam probably won't work very well because any disk changes are stored in RAM, including steam updates and game downloads.

**Comment by DraGiuS** [comment]
Oh, and another thing, adding playonlinux, virtualbox and geany will be possible on the same livecd ?
It will be cool for an out of the box installation

**Comment by nemasu** [comment]
Yeah, it's possible. Maybe making a new one would be better though, not just for the stock KDE image. What's the general idea of what you want to use it for?

By the way, I just finished updating KDE to latest version. I'm making a new ISO now.

**Comment by DraGiuS** [comment]
I want to use it for dev in C# (monodevelop, geany ?) , a bit of gaming (steam, playonlinux), and all the tasks of the default user (like writing mails,torrent, reading pdf, browsing,emulation,video editing,editing music, (amarok, musecore, listening music, github, ....) and kde on top of it.

**Comment by nemasu** [comment]
I see. Well, I was thinking about making a dev ISO anyways actually, I guess adding steam, wine, and playonlinux wouldn't hurt. Gonna be a pretty big image though, guess we'll see.

**Comment by DraGiuS** [comment]
Yeah, a new flavor would be good

**Comment by nemasu** [comment]
I'll try these, and if it's not ridiculously large I'll upload it, or maybe torrent.
If you have anything to add (or suggestions to remove), let me know.
I'll probably call it KDE-Everything.

Dev:
dev-meta(gcc, autotools, etc), mono, monodevelop, geany, qtcreator, rust, erlang, go, nodejs

Game:
wine, playonlinux, emulators( desmume, mednafen, mupen64plus, pcsx2 ), steam

Multimedia:
kdenlive, krita, clementine, vlc, gimp, deadbeef, digikam, inkscape, musescore

Other:
firefox, chromium, virtualbox, qemu, dosbox, gparted, hexchat, k3b, nvidia, openvpn, pidgin, qupzilla, transmission, ttf-sazanami, ttf-noto, otf-ipafont, network-manager-applet

**Comment by DraGiuS** [comment]
I'm good, if it's under 3.6gb

**Comment by DraGiuS** [comment]
Maybe codeblocks and kdevelop are not necessary. Same for amarok.

**Comment by nemasu** [comment]
OK sounds good.

**Comment by DraGiuS** [comment]
If you can replace the default sddm theme, i recommend it : https://github.com/MarianArlt/sddm-chili

Or maybe replace sddm with slim, with this theme : https://github.com/adi1090x/slim_themes/tree/master/themes/minimal
Which i use on gentoo.

**Comment by DraGiuS** [comment]
Git clone repo then 
sed -i 's/Current=/Current=chili/' /etc/sddm.conf

**Comment by nemasu** [comment]
Ugh, there's a bug with virtualbox guest additions with the kernel being used. I'm gonna update that before making this ISO. In the meantime, I've updated the KDE live CD with kdenlive added.

**Comment by nemasu** [comment]
I'm going to close this issue since the plasma live CD is updated, I made a new issue for the other livecd.
