### ISSUE TITLE
Create new KDE based livecd.

### ISSUE THREAD

**Issue by nemasu** [nemasu/noop-linux#5]
Current package list:

Dev:
dev-meta(gcc, autotools, etc), geany, qtcreator, nodejs, brackets, unityhub, code

Game:
playonlinux, emulators( desmume, mednafen, mupen64plus, pcsx2 ), steam, lutris, discord

Multimedia:
kdenlive, clementine, vlc, gimp, inkscape, musescore, blender, googlemusicmanager, spotify-client

Other:
chromium, virtualbox, qemu, gparted, hexchat, nvidia, openvpn, pidgin, qbittorrent, ttf-sazanami, ttf-noto, otf-ipafont, ttf-liberation, network-manager-applet

**Comment by DraGiuS** [comment]
Can you package lutris and blender and add them to the live cd ?

**Comment by nemasu** [comment]
Sure, I don't have them in the repo, so I'll have to add them first.

**Comment by nemasu** [comment]
The ISO is 4.0 GB.
It's here for now:
https://nooplinux.org/dist/noop-everything-20180906.iso
My host is very slow, so I might add a magnet link for it.

If it's too big, i think Erlang can go. Not sure what else though.

**Comment by DraGiuS** [comment]
Can you remove erlang, deadbeef, digikam, qupzilla,juk  and chromium or firefox ?

**Comment by nemasu** [comment]
After those are removed, it comes to 3.8G (4063211520), that OK?

**Comment by DraGiuS** [comment]
You can remove the support for mono and krita, i do not need these software. And my usb is only 3.66 gb

**Comment by DraGiuS** [comment]
Again, thanks for your work.

**Comment by nemasu** [comment]
No problem! I think the size will be OK now, I'll keep it like this unless someone requests something to be added.

**Comment by nemasu** [comment]
@DraGiuS 3.7G ... almost there...
EDIT: I got rid of /usr/share/gtk-doc/html , I doubt anyone will miss that.
New size is  3.6G (3850039296).

**Comment by DraGiuS** [comment]
Good

**Comment by nemasu** [comment]
Okay, it's uploaded, give it a try. It's on the try it page along with a magnet link which should be much faster since it includes the web source as well.

**Comment by DraGiuS** [comment]
It works quite good, but i dont need k3b, go and rust.
Finally, inkscape seems to be good, and if you can add brackets and discord, it will be perfect for me.
Thanks.

**Comment by DraGiuS** [comment]
Finally, the iso size no matter, you can include wine.

**Comment by DraGiuS** [comment]
With the new kde plasma released, a new iso will be perfect

**Comment by nemasu** [comment]
Ah is that out already? OK I'll take a look.

**Comment by DraGiuS** [comment]
And i think : 
Add brackets,inkscape,unityhub (new package), discord(flatpak ?),gamehub (new)
Remove wine,k3b, go,rust,transmission,dosbox, mono, monodevelop

**Comment by nemasu** [comment]
@DraGiuS 
Thanks! Turn out the new Plasma version requires a new version of Qt, so this will take a bit of time.
Edit: KDE is updated, will look at brackets and the other new packages next.

**Comment by DraGiuS** [comment]
Thanks again .

**Comment by nemasu** [comment]
Hello @DraGiuS 
I can't seem to successfully build brackets, so i tried repackaging the official Debian release. But I'm running into problems running it, specifically this exact problem:
https://github.com/adobe/brackets/issues/14485

What distro do you usually use it on?

**Comment by DraGiuS** [comment]
I use the flatpak version on archlinux

**Comment by DraGiuS** [comment]
If you can't even package it, it can go, and you can add vscode (insiders is great), for example.

**Comment by nemasu** [comment]
Ok, I'll try a few more things. I added flatpak to noop yesterday which runs Brackets fine, so that's an option too.

Update: I managed to get the prepackaged version working with an older version of sqlite.

**Comment by DraGiuS** [comment]
Add spotify with flatpak or with your package manager could be a good idea, what do you think ?

**Comment by nemasu** [comment]
Sure, I have google music in the repo too, I'll try to repackage the debian release.

**Comment by DraGiuS** [comment]
And we can replace deadbeef with GoogleMusicManager, even if it's not an open source software.

**Comment by DraGiuS** [comment]
Just remove chromium,mono and monodevelop, (and add code instead if you want, and if it fit with an 3.5G iso) and all good for me. 
And why not sddm instead of lxdm ?

**Comment by nemasu** [comment]
Playonlinux requires wine.

Current size is at 3.7G. Should I get rid of playonlinux and wine?

**Comment by DraGiuS** [comment]
Yes, we have lutris. I saw that you have ppssspp packaged, we can add it to the bundle.
Like i said, we can replace lxdm with sddm with this theme : https://github.com/MarianArlt/sddm-chili or https://github.com/RadRussianRus/sddm-slice
This command would do the job : sed -i 's/Current=/Current=chili/' /etc/sddm.conf
or maybe create a package like : https://aur.archlinux.org/packages/sddm-theme-kde-plasma-chili/

**Comment by DraGiuS** [comment]
Last thing, can you try to package auryo and add it : http://auryo.com/#downloads, it could be easy with the appimage already build. (and remove clementine, which is replaced by googlemusicmanager).
Thanks you.

**Comment by nemasu** [comment]
OK it's up.
https://nooplinux.org/dist/noop-everything-20181102.iso

**Comment by DraGiuS** [comment]
Ok, it look good.
Brackets need to have an icon.
Now,  i propose to change the installation mode, with calamares for example : https://calamares.io
What's the default password for dnsmasq ?

**Comment by nemasu** [comment]
Ah, I fixed the icon, but it won't show up till the image is regenerated.
Calamares looks interesting, I'll take a look at it.
dnsmasq the user? Looks like no password has been set.
I'm gonna close this issue since the live cd is done.

**Comment by DraGiuS** [comment]
Yeah you can try some things with calamares or refracta installer.
And unityhub has been updated to 1.2

**Comment by DraGiuS** [comment]
Oh and add https://photoeditor.polarr.co/ and https://www.onivim.io, remove geany
