### ISSUE TITLE
Suggestions of packages for the everything flavor

### ISSUE THREAD

**Issue by DraGiuS** [nemasu/noop-linux#9]
Hello, i would ask you for adding these softwares and package them to the everything live cd.
Replace geany by onivim.
And maybe replace inkscape with polarr.

**Comment by DraGiuS** [comment]
I remind you that

**Comment by nemasu** [comment]
I can't find the Polarr source code, is it open source?

**Comment by DraGiuS** [comment]
Humm.. I don't find any source code too 
Can you add devhub, notable and soundnode too ?
https://github.com/devhubapp/devhub https://github.com/notable/notable https://github.com/Soundnode/soundnode-app

And : Spicetify-cli : https://github.com/khanhas/spicetify-cli

Thank you for your great work.

**Comment by DraGiuS** [comment]
Maybe we will need to update the live cd soon.
We can replace Lyricfier with https://github.com/marioortizmanero/spotify-music-videos

**Comment by nemasu** [comment]
evesetup seems to be broken at the moment.

I've been thinking of making a web interface for building custom ISOs, gonna look into how much time this will take. Going to start with a local version first I think. For now I've added yarock.

**Comment by DraGiuS** [comment]
Don't worry, but the last time i used it, it was fonctionnal...
It can easily be replaced by lutris, which is fonctionnal now.
Now we can just focus on the other package i listed.
Thank you anyway, i saw that you updated many packages ! 

I was wondering, do the actual installer support the installation in a different language like french ?

**Comment by protonesso** [comment]
Nemasu, add initial support for musl libc

2019年10月21日(月) 13:02 Yosh <notifications@github.com>:

**Comment by nemasu** [comment]
I no longer have time to maintain noop, so I'm halting development.
